CREATE TABLE `cards` (
	`id` text PRIMARY KEY NOT NULL,
	`player_name` text NOT NULL,
	`year` integer,
	`brand` text,
	`set_name` text,
	`card_number` text,
	`team` text,
	`sport` text DEFAULT 'baseball' NOT NULL,
	`variant` text,
	`condition` text,
	`graded` integer DEFAULT false NOT NULL,
	`grade_company` text,
	`grade_value` real,
	`purchase_price` real,
	`purchase_date` text,
	`purchase_source` text,
	`location` text,
	`image_front` text,
	`image_back` text,
	`notes` text,
	`tags` text DEFAULT '[]',
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	`updated_at` text DEFAULT (datetime('now')) NOT NULL
);
